# soon

# %s to get permission
noPermissionMessage: "§cSorry, not today! Missing permission: %s"

autoUpdate: true

storageType: "MYSQL"

databaseCredentials:
  hostname: "localhost"
  port: 3306
  databaseName: test
  username: "localtest"
  password: "password"
  customUrl: ""